name: Publish Python package

on:
  push:
    tags:
      - 'v*.*.*'  # triggers on version tags like v0.2.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build twine
      - name: Build distribution
        run: python -m build --sdist --wheel
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.USERNAME }}
          TWINE_PASSWORD: ${{ secrets.
          PASSWORD }}
        run: twine upload dist/*
